"use client"
import React from "react"
import { Phone, Mail, MapPin, Download, Home } from "lucide-react";

import jsPDF from "jspdf";
import { useRouter } from "next/navigation";
import { useSelector } from "react-redux";
import { RootState } from "@/store/store";
import moment from "moment";

const contactOptions = [
  {
    id: 1,
    title: "Call Us",
    value: "(555) MEDI-BOOK",
    sub: "Mon-Fri: 8AM–6PM",
    icon: <Phone className="w-6 h-6 text-blue-500" />,
    link: "tel:555MEDIBOOK",
  },
  {
    id: 2,
    title: "Email Us",
    value: "help@medibook.com",
    sub: "24/7 Support",
    icon: <Mail className="w-6 h-6 text-blue-500" />,
    link: "mailto:help@medibook.com",
  },
  {
    id: 3,
    title: "Visit Us",
    value: "123 Health St",
    sub: "Medical District",
    icon: <MapPin className="w-6 h-6 text-blue-500" />,
    link: "https://maps.google.com/?q=123+Health+St",
  },
];

export default function ContactSection() {
  // Example JSON data (replace with your API/state values)
  const formData = useSelector((state: RootState) => state.form)
  //  name: `${formData?.firstName || ""} ${formData?.lastName || ""}`,
  //             email: formData?.email|| "",
  //             phone: formData?.phone || "",
  //             reason: formData?.reason || ""

  const appointmentData = {
    name: `${formData?.firstName || ""} ${formData?.lastName || ""}`,
    doa: moment(formData?.doa).format("ll"),
    email: formData?.email || "",
    phone: formData?.phone || "",
    doctor: formData?.selectDoctor?.name || "",
    department: formData?.selectDoctor?.specialty || "",
    date: formData?.doa ? moment(formData?.doa).format("ll") : "-",
    time: formData?.selectedTime || "-",
    hospital: "City Medical Center",
  };


  const route = useRouter()
  const generatePDF = () => {
    const doc = new jsPDF();

    // Title - centered
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Appointment Confirmation", 105, 20, { align: "center" });
    doc.setLineWidth(0.5);
    doc.line(40, 25, 170, 25); // underline

    // Patient Information Section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Patient Information", 20, 40);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    const leftColX = 25;   // labels aligned
    const valueColX = 70;  // values aligned

    doc.text("Name", leftColX, 50);
    doc.text(":", leftColX + 35, 50);
    doc.text(appointmentData.name, valueColX, 50);

    doc.text("Date Of Appoinment", leftColX, 60);
    doc.text(":", leftColX + 35, 60);
    doc.text(appointmentData.doa, valueColX, 60);

    doc.text("Email", leftColX, 70);
    doc.text(":", leftColX + 35, 70);
    doc.text(appointmentData.email, valueColX, 70);

    doc.text("Phone", leftColX, 80);
    doc.text(":", leftColX + 35, 80);
    doc.text(appointmentData.phone, valueColX, 80);

    // Appointment Details Section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Appointment Details", 20, 100);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    doc.text("Doctor", leftColX, 110);
    doc.text(":", leftColX + 35, 110);
    doc.text(appointmentData.doctor, valueColX, 110);

    doc.text("Department", leftColX, 120);
    doc.text(":", leftColX + 35, 120);
    doc.text(appointmentData.department, valueColX, 120);

    doc.text("Date", leftColX, 130);
    doc.text(":", leftColX + 35, 130);
    doc.text(appointmentData.date, valueColX, 130);

    doc.text("Time", leftColX, 140);
    doc.text(":", leftColX + 35, 140);
    doc.text(appointmentData.time, valueColX, 140);

    doc.text("Hospital", leftColX, 150);
    doc.text(":", leftColX + 35, 150);
    doc.text(appointmentData.hospital, valueColX, 150);

    // Footer
    doc.setTextColor(100);
    doc.setFontSize(10);
    doc.text("Generated by MediBook System", 105, 280, { align: "center" });

    // Save
    doc.save("appointment-confirmation.pdf");
  };



  return (
    <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow p-6 space-y-6">
      {/* Title */}
      <div className="flex items-center gap-2 text-lg font-semibold text-gray-800">
        <Phone className="w-5 h-5 text-blue-500" />
        Need to Make Changes?
      </div>

      {/* Contact Options */}
      <div className="grid md:grid-cols-3 gap-4">
        {contactOptions.map((item) => (
          <a
            key={item.id}
            href={item.link}
            className="flex flex-col items-center justify-center bg-blue-50 p-4 rounded-xl shadow-sm hover:bg-blue-100 transition"
          >
            {item.icon}
            <h3 className="mt-2 font-medium text-gray-800">{item.title}</h3>
            <p className="text-blue-600 font-semibold">{item.value}</p>
            <p className="text-gray-500 text-sm">{item.sub}</p>
          </a>
        ))}
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 justify-center">
        <button onClick={generatePDF}
          className="flex items-center gap-2 bg-gray-100 px-5 py-2 rounded-lg shadow hover:bg-gray-200 transition">
          <Download className="w-4 h-4" />
          Download Confirmation PDF
        </button>
        <button onClick={() => route.push("/")} className="flex cursor-pointer items-center gap-2 bg-blue-600 text-white px-5 py-2 rounded-lg shadow hover:bg-blue-700 transition">
          <Home className="w-4 h-4" />
          Return to Homepage
        </button>
      </div>
    </div>
  );
}
