// app/layout.tsx
import type { Metadata } from "next";
import { FaHeart } from "react-icons/fa";
import React from "react";
import ClientProvider from "@/app/ClientProvider"; // ✅ new client wrapper
import Link from "next/link";

export const metadata: Metadata = {
    title: "Appointment Application F",
    description: "Generated by create next app",
};

const Navbar = () => {
    return (
        <header className="container mx-auto p-4 border-b-2">
            <div className="flex justify-between items-center">
         <Link href={"/"}>
                <div className="flex py-2 items-center cursor-pointer">
                    <div className="flex justify-center items-center w-10 h-10 bg-blue-600 text-white font-bold text-2xl rounded mr-2">
                        <FaHeart />
                    </div>
                    <div>
                        <h2 className="font-bold text-slate-800 text-xl">MediBook</h2>
                        <div className="text-gray-500 text-sm">Clinic</div>
                    </div>
                </div>
                </Link>
                <div className="hidden lg:block">
                    <div className="flex items-center">
                        <div>
                            <div className="text-black font-bold">(555) MEDI-BOOK</div>
                            <div className="text-gray-500 text-sm">24/7 Support Available</div>
                        </div>
                        <div className="pl-2">
                            <button className="bg-blue-600 py-3 px-5 text-white rounded font-bold">
                                Call Now
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    );
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
      <section>
          <Navbar />
                <ClientProvider>{children}</ClientProvider>
                </section>
    );
}
